name: 'Install uv'
description: 'Install uv using community action'
runs:
  using: composite
  steps:
    - name: Install uv
      shell: bash
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
